"""milestone A: incomes, recurring expenses, price snapshots, sip schedules

Revision ID: 32511e50be85
Revises: 376a2676f554
Create Date: 2026-06-09 18:34:46.078135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import wealthlog.db.types


# revision identifiers, used by Alembic.
revision: str = '32511e50be85'
down_revision: Union[str, Sequence[str], None] = '376a2676f554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incomes_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incomes_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incomes_date'), ['date'], unique=False)

    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_id', 'date', name='uq_price_snapshot_investment_date')
    )
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_snapshots_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_snapshots_investment_id'), ['investment_id'], unique=False)

    op.create_table('recurring_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='recurrencefrequency'), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_generated', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_expenses_category_id'), ['category_id'], unique=False)

    op.create_table('sip_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sip_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sip_schedules_investment_id'), ['investment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sip_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sip_schedules_investment_id'))

    op.drop_table('sip_schedules')
    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_expenses_category_id'))

    op.drop_table('recurring_expenses')
    with op.batch_alter_table('price_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_snapshots_investment_id'))
        batch_op.drop_index(batch_op.f('ix_price_snapshots_date'))

    op.drop_table('price_snapshots')
    with op.batch_alter_table('incomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incomes_date'))
        batch_op.drop_index(batch_op.f('ix_incomes_category_id'))
        batch_op.drop_index(batch_op.f('ix_incomes_account_id'))

    op.drop_table('incomes')
    # ### end Alembic commands ###
