"""initial schema

Revision ID: 376a2676f554
Revises: 
Create Date: 2026-06-08 18:35:55.832277

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import wealthlog.db.types

# revision identifiers, used by Alembic.
revision: str = '376a2676f554'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('EXPENSE', 'INCOME', name='categorytype'), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'type', name='uq_category_name_type')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_pair', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_currency_pair'), ['currency_pair'], unique=False)
        batch_op.create_index(batch_op.f('ix_fx_rates_fetched_at'), ['fetched_at'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_type', sa.Enum('STOCK_IN', 'STOCK_US', 'MF', 'GOLD_ETF', 'FD', name='assettype'), nullable=False),
    sa.Column('currency_native', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_investments_symbol'), ['symbol'], unique=False)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('limit_amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'month', 'year', name='uq_budget_category_month_year')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_date'), ['date'], unique=False)

    op.create_table('fd_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('principal', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('interest_rate', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('compounding', sa.Enum('SIMPLE', 'ANNUAL', 'SEMI_ANNUAL', 'QUARTERLY', 'MONTHLY', name='compoundingfrequency'), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fd_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fd_details_investment_id'), ['investment_id'], unique=True)

    op.create_table('prices_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('price_native', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('price_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('fx_rate_used', wealthlog.db.types.DecimalText(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prices_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_cache_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_cache_investment_id'), ['investment_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('investment_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'SIP', name='transactiontype'), nullable=False),
    sa.Column('units', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('price_per_unit', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('fx_rate_used', wealthlog.db.types.DecimalText(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_investment_id'), ['investment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_investment_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))

    op.drop_table('transactions')
    with op.batch_alter_table('prices_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_cache_investment_id'))
        batch_op.drop_index(batch_op.f('ix_prices_cache_fetched_at'))

    op.drop_table('prices_cache')
    with op.batch_alter_table('fd_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fd_details_investment_id'))

    op.drop_table('fd_details')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_category_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_account_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_symbol'))
        batch_op.drop_index(batch_op.f('ix_investments_asset_type'))

    op.drop_table('investments')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_fx_rates_currency_pair'))

    op.drop_table('fx_rates')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_name'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
