"""B4: add investment.sector

Revision ID: 4a58bfdfca0b
Revises: 32511e50be85
Create Date: 2026-06-09 22:32:55.266453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import wealthlog.db.types


# revision identifiers, used by Alembic.
revision: str = '4a58bfdfca0b'
down_revision: Union[str, Sequence[str], None] = '32511e50be85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
