"""2b liabilities table

Revision ID: 980cbd7b6e1e
Revises: c2d3e4f5a6b7
Create Date: 2026-06-10 13:34:53.632517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import wealthlog.db.types


# revision identifiers, used by Alembic.
revision: str = '980cbd7b6e1e'
down_revision: Union[str, Sequence[str], None] = 'c2d3e4f5a6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_inr', wealthlog.db.types.DecimalText(), nullable=False),
    sa.Column('category', sa.Enum('LOAN', 'CREDIT_CARD', 'OTHER', name='liabilitycategory'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.CheckConstraint('CAST(amount_inr AS REAL) >= 0', name='ck_liability_amount_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_liabilities_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_liabilities_name'), ['name'], unique=False)

    # NOTE: autogen also proposed re-typing investments.asset_type to an Enum because
    # AssetType gained BENCHMARK; wealthlog intentionally stores it as VARCHAR, so that
    # alter is dropped (consistent with earlier migrations).
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_liabilities_name'))
        batch_op.drop_index(batch_op.f('ix_liabilities_category'))

    op.drop_table('liabilities')
    # ### end Alembic commands ###
