"""C3: alert_rules and alert_events

Revision ID: ac8711fd3f88
Revises: 4a58bfdfca0b
Create Date: 2026-06-09 22:46:12.662999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import wealthlog.db.types


# revision identifiers, used by Alembic.
revision: str = 'ac8711fd3f88'
down_revision: Union[str, Sequence[str], None] = '4a58bfdfca0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('PRICE_DROP', 'BUDGET_PCT', 'SIP_DUE', name='alertkind'), nullable=False),
    sa.Column('threshold', wealthlog.db.types.DecimalText(), nullable=True),
    sa.Column('investment_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_investment_id'), ['investment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_kind'), ['kind'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('fired_on', sa.Date(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_fired_on'), ['fired_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_rule_id'), ['rule_id'], unique=False)

    # Note: investments.asset_type stays VARCHAR (StrEnum stored as text); the
    # autogenerated native-Enum type change for the new BENCHMARK value is omitted.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_rule_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_fired_on'))

    op.drop_table('alert_events')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_kind'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_investment_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rules_category_id'))

    op.drop_table('alert_rules')
    # ### end Alembic commands ###
